label chap2_2:
    "Tôi nhìn vào khối cầu đang tỏa ra thứ ánh sáng xanh bao phủ lấy tầm mắt đó. Đây là một cái lõi năng lượng đấy? Nếu đụng vào nó bằng tay không thì sẽ chẳng ổn chút nào đâu."
    main "Tốt nhất mình nên bỏ qua vì cũng đâu cần gì đâu nhỉ?"
    "Sau một lúc cân nhắc kỹ lưỡng tôi quyết định mặc kệ thứ đó."
    "Hừm, như vậy chắc đủ cho hôm nay rồi. Dù sao thì tôi cũng đâu có ý định chế tạo lại một thứ gì đó giống hệt đâu mà."
    "???" "Này! Ai ở trong đó vậy!"
    main "Tiêu rồi, đổi ca trực ư? Sao lại nhanh vậy? Đành phải đi theo con đường đấy nhỉ."
    "Chẳng còn thì giờ để suy nghĩ, tôi vội thoát bằng con đường đã chuẩn bị sẵn để sử dụng vào những lúc nguy cấp."
    "Tôi vẫn còn hơn bốn tuần nữa để sống, không thể để bị bắt lãng xẹt vậy được."
    play sound running
    "Ngay khi rời khỏi con hẻm, tôi cố chen vào dòng người đông đúc trên phố và đi theo một hình dạng bất quy tắc nhất có thể với mong muốn cắt đuôi được bất cứ kẻ nào đang theo sau lưng mình."
    play sound opendoor
    "Mở cửa trong trạng thái rũ rượi cả cơ thể lẫn tinh thần, tôi ngay lập tức bị thêm một đòn công kích chẳng mấy là bất ngờ tỏa ra từ phía trong căn nhà."
    scene bg house
    "Thế nhưng, tôi lại quên mất một điều rằng thiết bị theo dõi vẫn đang ở trong cánh tay của mình."
    "Mở cửa trong trạng thái rũ rượi cả cơ thể lẫn tinh thần, tôi ngay lập tức bị thêm một đòn công kích chẳng mấy là bất ngờ tỏa ra từ phía trong căn nhà."
    main "Ư... làm sao để tống cô ta đi nhỉ?"
    "Việc cô gái này xuất hiện, tâm trí tôi như đang bị bào mòn từng ngày vậy."
    "Dù sao thì thứ thuốc kia vẫn giúp tôi chút ít, thế nhưng việc hít thở một bầu không khí như rải đinh nhọn thế này thật chẳng tốt cho sức khỏe chút nào."
    "Nhưng tôi cũng chẳng thể mang cô nàng này đi đâu xa, hay đúng hơn thì tôi còn chẳng dám đụng vào cô ta nữa."
    "Chỉ đứng gần thôi cũng khiến đầu óc tôi mụ mẫn, tâm trí lu mờ, cơ thể dần mất đi sức lực và có nguy cơ khụy xuống bất cứ khi nào thì làm sao tôi có thể mang cô ta đi đâu chứ?"
    main "Hay là báo cảnh sát nhỉ?"
    "Đã cất công cho cô ta ở lại đây thì báo cảnh sát liệu còn ý nghĩa gì à? Thay vì đó thì cứ săm soi cô gái này để thõa mãn trí tò mò có phải hơn không."
    "Với lại, tôi vẫn còn nhiều điều cần xác minh, thế nên cứ để cô ta ở đây là tiện nhất rồi."
    "Cơ mà cô ta cứ nằm lỳ ở đây thì bất tiện cho tôi thật đấy, có cách nào để gọi cô ta dậy mà không đụng vào không nhỉ?"
    "Sau một hồi lâu suy nghĩ và thử nghiệm, tôi đã đưa ra vài kết luận. Tác động vật lý lên cô nàng, ví dụng như dùng gậy hay ném món gì đó tới là hoàn toàn vô dụng."
    "Dùng âm thanh như la hét hay chấn động rung như đập sàn nhà cũng chẳng có hiệu quả. Mùi hương cũng không. Mọi cách để đánh thức một con người bình thường dậy đều không khả quan."
    "Điều đó chứng tỏ cô ta không bình thường."
    "Cơ mà tôi cũng chẳng biết gì về cô gái này, hay nói đúng hơn thì tôi chẳng biết gì về con gái cả."
    "Những điều nêu ra trong sách vở quá mơ hồ, họ chỉ miêu tả sơ sài về một sinh vật loài người có mái tóc dài, cơ thể thon gọn, nhiều đường cong cùng với một vẻ đẹp đặc biệt."
    "So với những khái niệm trong sách thì cô gái này quá khác biệt. Cô ta cũng có một mái tóc dài, một cơ thể thon gọn, nhiều đường con và một vẻ đẹp không sao cưỡng lại được. Thế nhưng mọi chuyện không chỉ có thể."
    "Trong sách cũng miêu tả rằng phụ nữ vẫn là loài người, vậy mà cô gái này đã hai ngày rồi không ăn, cũng chẳng có chút dấu hiệu nào là đang hít thở."
    main "Giống như... cô ta đã chết vậy."
    "Ấy vậy mà cơ thể đó lại không thối rữa, làn da vẫn đàn hồi và hồng hào. Hiện tôi chẳng có khả năng để kiểm tra đồng tử nhưng tôi nghĩ nó vẫn bình thường."
    main "Vậy chẳng lẽ cô ta đúng là thứ mà tài liệu trong con tàu kia để cập?"
    "Nếu vậy thì còn phiền phức hơn dự định. Nhưng... cũng đồng thời thú vị hơn dư kiến!"
    scene black with dissovle
    pause (2)
    scene bg_ham with fade
    "Ngay bên dưới căn hầm ẩm thấp và bụi bặm, có một kẻ đang ngồi mò mẫm hàng tiếng đồng hồ để chế tạo ra một thứ trước vốn chỉ được cấp phép mới có thể sở hữu."
    "Và kẻ đó là tôi."
    "Hiện tại thì tôi đang thử chế tạo lại một bản sao y hệt con tàu ở trong con hẻm đó. Nếu có ai đó hỏi vì sao tôi lại làm vậy thì tôi chỉ có một lý do duy nhất."
    "Để giải trí."
    "Thì tôi không cần đến trường nữa, cũng chẳng cần phải làm bất cứ thứ gì được chính phủ giao phó nữa."
    "Nói cho chính xác thì tôi giống như đang bước vào kỳ nghỉ hưu cửa mình vậy."
    "Dù sao thì tính tới thời điểm hiện tại, tôi cũng chỉ còn vài tuần để sống. Thế nên sao lại không thể không làm chuyện mình muốn chứ."
    "Tôi rất thích máy móc, việc tạo ra một thứ gì đó dựa trên những mảnh ghép nhỏ khiến tôi cảm thấy khá phấn khích."
    "Nếu coi việc đi vào hẻm là một thói quen khó bỏ thì sở thích thật sự của tôi phải là chế tạo."
    "Nhìn những mẩu linh kiện nho nhỏ liên kết với nhau tạo thành một khối hoàn chỉnh luôn là thứ gì đó mà tôi chẳng bao giờ chán nổi."
    "Nhưng việc tháo chúng ra thì lại là chuyện khác."
    "Tuy vậy thì ngoài việc chế tạo con tàu này ra thì tôi còn một chuyện khác cũng muốn làm thử."
    "Chế tạo một con robot."
    "Việc chế tạo một thiết bị máy móc có thể vận hành thì chẳng đáng nói gì. Nhưng thứ tôi muốn tạo lại là một con robot có Trí Thông Minh Nhân Tạo kia kìa."
    "Một thứ như thế cần rất nhiều thời gian để phát triển nó. Nhưng với công nghệ hiện tại của loài người thì cũng không đến nổi khó khăn gì mấy."
    "Mà...trước đó, tôi phải hoàn thành con tàu này trước đã. Tôi dạo này đã lảng vảng ở khu vực được canh gác kia rồi. Vừa nãy lại còn bị phát hiện."
    "Với cái thiết bị theo dõi trên tay này tôi kiểu gì cũng bị tình nghi thôi. Cảnh sát sẽ có thể ập vào bất cứ lúc nào."
    "Không những thế, tôi có một thứ phải kiểm chứng."
    "Hự..."
    play sound heartbeat
    "Lồng lực tôi một lần nữa quặn đau báo hiệu giờ uống thuốc đã đến."
    "Đành phải bỏ dở công việc đang khiến tôi hứng thú, tôi bước từng bước lên cầu thang và rời khỏi căn hầm."
    "Dưới đó vốn không phải của tôi, từ lúc tôi chuyển đến đây thì nó đã ở đó rồi."
    "Nghe phong thanh thì nó vốn là chỗ trú ẩn của một tên trộm nào đó. Khi tôi nhận được căn nhà này thì họ có đề nghị với tôi về việc lấp lại căn hầm."
    "Thế nhưng với một con người cần không gian để làm việc như tôi thì nơi đó chẳng khác nào thiên đường. Vì vậy tôi đã từ chối việc lấp lại căn hầm và sử dụng nó như người sở hữu hợp pháp."
    "Nơi đó trở thành nơi tập kết chiến lợi phẩm của tôi cũng như để tôi thực hiện sở thích của mình."
    "Bình thường thì mấy con hẻm luôn có nhiều thứ thú vị và dễ kiếm hơn nhiều. Chỉ cần một vài cái xác máy cũ là tôi có thể có đủ bộ phận để chế tạo thứ gì đó hay ho rồi."
    "Tuy vậy tôi vẫn cảm thấy không an toàn cho lắm nên đã dùng một cái tủ để lấp đi lối ra vào căn hầm. Chỉ như vậy thì tôi mới an tâm sử dụng nó được. Ai mà ngờ được việc sẽ có một kẻ nào khác trốn ở đó chứ? Nên là..."
    scene bg_house with dissovle
    main "Cẩn tắc vô áy náy."
    play sound moving
    "Lồng ngực một lần nữa nhói lên như để chắc nhở, tôi buộc phải hướng mắt về cái hộp thuốc để trên tủ dù muốn hay không."
    "Một hộp thuốc không có nhãn, cũng chẳng có vỏ, chẳng rõ thành phần là gì, thế nhưng khi uống vô lại có tác dụng kiềm chế căn bệnh. Một thứ thuốc lạ lùng."
    "Trong lúc đi lấy thuốc, tôi đưa mắt về phía cô gái kì lạ từ trên trời rơi xuống. Chẳng biết bằng cách nào, cũng chẳng rõ chuyện gì đã xảy ra. Thế nhưng bằng một cách nào đó, cô ta đã nằm ở đó hơn một tuần."
    "Cơ thể cô ta chẳng hề thay đổi cho dù không ăn, không uống, cũng chẳng cần hít thở."
    "Cô ta không thối rữa đi, nhưng cũng chẳng có dấu hiệu nào rằng cô gái đó sẽ tỉnh lại."
    "Liệu tôi có nên mang cô ta xuống dưới tầng hầm cho an toàn không nhỉ? Lỡ có ai đó vào nhà đột xuất thì đó là ngày cuối của đời tôi mất."
    menu:
        "Đem xuống dưới hầm.":
            jump chap2_3:
        "Không đem xuống.":
            pass
    "Cơ mà tôi chẳng muốn lặp lại việc đó chút nào."
    "Thôi thì cứ để cô ta ở đây vậy."
    "Dừng việc nhìn chằm chằm vào thực thể bí ẩn đó, tôi lấy một viên thuốc từ trong hộp ra và bỏ vào miệng."
    "Cảm thấy quá lười để uống nước, tôi nuốt trôi luôn viên thuốc xuống cổ họng."
    "Lý trí tôi dần bừng tỉnh bởi vị đắng của thuốc, cũng như một phần nào trong tôi trở nên nhẹ nhõm và dễ kiểm soát hơn."
    "Mọi thứ đã gần như hoàn thành, giờ chỉ còn một việc duy nhất là năng lượng nữa thôi."
    "Vì đã không lấy cái lõi năng lượng kia nên giờ đây tôi phải nghĩ ra cách khác để cấp năng lượng cho nó mới được."
    "Chẳng biết dùng thứ gì cả nên tôi đành phải sử dụng nguồn điện. Nhưng điện thì tôi nghĩ nó sẽ không đủ để cho cái 'Con Quái Thú' này chạy nổi đâu."
    "Lí do tôi gọi nó là 'Quái thú' vì nó rất ngốn điện. Bởi thế nên tôi đã tạo ra một máy phát điện trong khu vực gần động cơ."
    "Tận dụng nguồn gió ma sát với tàu trong lúc bay là có thể làm quay tubin rồi. Nhưng nó không thể quá to được nên tôi đã tận dụng những kiến thức và công nghệ của thời đại và tạo ra thêm máy khuết đại năng lượng."
    "Nghe thì con tàu này lại có vẻ như rất được việc đấy nhưng so với nguồn năng lượng mà các loại tàu bay thời nay dùng thì chỉ như so sánh cốc nước muối với biển thôi."
    "Vì tận dụng nguồn gió, hay nói cách khác là sự chuyển động của không khí khi con tàu bay trong khí quyển nên gần như là nó sẽ chạy rất trơn tru mà chẳng tốn một chút nguyên liệu thêm nào nữa."
    "Nhưng khi ra ngoài không gian thì lại khác. Nhưng mà tôi có định ra ngoài không gian đâu, nên chắc như này là ổn."
    main "Mà thôi. Giờ đi ngủ, chứ làm lao lực hai ngày trời khéo lại chết trước khi chết vì bệnh mất."
    "Nghĩ thế nên tôi đi vào phòng rồi ngủ."
    scene black with dissovle
    pause(1)
    scene bg_ham with fade
    main "Được rồi chạy thử xem nào."
    "Trước khi muốn tubin trong máy phát điện chạy nhờ sức gió thì tôi phải cho nó một nguồn năng lượng để cho nó bay trước đã."
    "Nên là tôi đã chuẩn bị một thứ gần giống như pin dự trữ phòng tình huống hỏng máy phát điện để còn năng lượng đáp xuống khẩn cấp. Cũng như trước khi bay lên trời."
    "Giờ việc của tôi là nạp đầy điện thôi."
    "Lấy máy vặn ốc tự động, tôi cạy phần ống dẫn dây trong nhà ra.Sau đó, tôi nối dài nó xuống tầng hầm. Cắm nó vào một cái máy khuết đại dòng điện khác nhỏ hơn để nạp điện cho pin dự phòng."
    play sound machine
    main "Cái này vào đây, còn cái này... nối vào đây nữa là xong. Phù."
    main "Chỉ còn việc cắm nó vào phần vốn chứa lõi của cỗ máy thôi."
    "Nói đoạn, tôi kéo đoạn dây to bằng cả cổ tay đến gần cỗ máy, leo lên phần thân nó bằng thang bảo trì và cắm phần chốt dây vào ngay phía trên phần lõi."
    play sound electric3
    "Thế nhưng, vào khoảng khắc mà tôi cắm chốt dây vào, mọi thứ xung quang liền bị bao phủ bởi một màu đen sâu thẳm."
    main "Mất điện à?"
    main "Mà cũng không đúng lắm, thời buổi này mất điện còn hiếm hơn việc trúng số nữa."
    main "Thôi xong, nếu không phải mất điện thì chỉ còn một cách để giải thích."
    "Cỗ máy này đã rút hết toàn bộ điện nơi đây. Và nơi đây nói chính xác thì là thành phố này."
    "Bởi lẽ nguồn điện trong nhà tôi liên kết với toàn bộ căn nhà trong chung cư này"
    "Và nguồn điện của chung cư lấy một phần tù trụ điện tổng trong thành phố."
    main "Nhưng chỉ với một viên pin dự phòng thôi mà đã như thế à?"
    "Dù biết nó sẽ rất ngốn điện nhưng tôi không ngờ là nó lại khủng khiếp đến thế."
    main "Chuyện này có vẻ không ổn lắm nhỉ?"
    "Thứ gì đó để chiếu sáng cái đã."
    "Lần mò từng bước trong bóng tối, tôi leo xuống khỏi thang bảo trì và an toàn đặt chân xuống sàn nhà."
    "Trong lúc tôi đang quơ ngang tay, cố xác định lại khung cảnh xung quanh thừ từ phía sau lưng..."
    "Một luồng sáng xanh bất ngờ đổ bộ và bao phủ lấy cả tầng hầm."
    "Bất giác quay lưng, tôi cố nhìn vào thứ đang tỏa ra sắc xanh huyền ảo đó."
    "Từ khe hở của thứ kết cấu không mấy bền bỉ, con tàu tôi vừa chế đạo đang ánh thên thứ màu lam rực rỡ hệt như con tàu nằm sâu phía trong con hẻm."
    "Ngay lập tức bị thu hút, tôi tiến đến gần con tàu và mở buồng lái ra. Cánh cửa bỗng bật mở cũng với một làn khói trắng hòa vẫn vào ánh sáng xanh mờ ảo tạo nên một cung cảnh đầy ấn tượng."
    "Nhìn vào bảng điều khiển đang được bật lên trong con tàu, đập vào mắt tôi chính là một màn hình duy nhất hiển thị nguồn năng lượng hiện tại."
    "Ba mươi bảy phần trăm."
    main "Thứ này hao năng lượng đến mức nào vậy chứ?"
    "Lượng điện đủ cho cả một thành phố dùng và được khuết đại lên 10 phần trăm mà chỉ sạc được ba mươi bảy phần trăm? Tôi bắt đầu lo lắng liệu những máy phát điện của tôi có đủ để gánh nổi cả cái thứ này bay lên được không."
    "Tuy phàn nàn là thế, tôi vẫn bị trí tò mò thu hút và ngồi vào bên trong. Ngồi xuống cái ghế lấy ra từ một cỗ xe cũ vứt lây lất đầu đường."
    "Tôi đặt tay lên cái cần điều khiển lấy từ một cái điều khiển từ xa dành cho drone."
    "Ấn nút đóng cửa, tôi từ từ quan sát chuyển động có phần hơi chậm chạp của cánh cửa kính. Được thiết kế như một cái cửa kéo để phù hợp với không gian, thay vì một cái cửa mở như bản gốc."
    main "Hệ thống phòng thủ, check. Rada, check. Nút thoát hiểm, check. Cảm biến quang phổ, cảm biến nhiện, check. Hộp dụng cụ và một vài bộ phận để thay thế, check."
    main "Pin dự trữ, ba mươi bốn phần trăm, check."
    main "Tất cả điều được kết nói với bảng điều khiển. Còn thiếu thứ gì nữa không nhỉ...?"
    main "À phải rồi! Camera sau!"
    "Nhận thấy điều mình cần làm tiếp theo, tôi ấn nút mở cửa với ý định ra ngoài thực hiện tiếp công việc. Thế nhưng, bằng một cách nào đó, cái nút không hoạt động."
    main "Hả? Chuyện gì nữa đây, khi nãy vẫn còn đóng lại được mà?"
        #play sound rầm
        "Trong lúc tôi lấy hộp dụng cụ để kiểm tra lại lỗi, một âm thanh lớn phát ra ngay gần đây khiến tôi giật bắn mình và đập đầu vào phần trên của con tàu."
        main "Ui! Đau!"
        "Kế đến, một loạt âm thanh nghe như tiếng bước chân phát ra dồn dập trên đầu tôi. Ngửa cổ lên nhìn, đập vào mắt tôi chỉ có lớp vỏ kim loại của con tàu, chẳng thể nhìn thấy gì hơn."
        "Và cho dù không có con tàu ở đây thì thứ tôi thấy cũng chỉ là lớp trần bê tông."
        "Có ai đó đang ở trong nhà tôi, hơn nữa còn rất nhiều."
    main "Chết tiệt! Chuyện gì đang xảy ra ở trên đó vậy!"
    "Tôi không còn kiềm chế được bản thân, vội vàng ấn lia lịa vào cái nút mở cửa. Nhưng tất nhiên, không hoạt động thì có ấn cách mấy thì vẫn là không hoạt động."
    main "Cô ta còn ở trên đó mà!"
    "Cô gái đó, con robot được cử đến để tìm tôi, cũng là manh mối duy nhất mà con tàu kia để lại đang ở trên đó. Vậy mà giờ tôi lại ở đây, bị nhốt trong một con tàu được chế tạo nên từ một mớ hỗn độn."
    "Đấm vào tấm kính trước mặt, tôi gần như buông bỏ. Nhưng kẻ ở trên cũng bắt đầu mò được xuống đây."
    "Tôi biết những kẻ đó là ai. Đơn giản mà nói, sau khi cả một thành phố đột ngột mất điện như thế thì phía trên kia chắc chắn là những người đang được trang bị vũ khi đầy đủ với kiến thức võ thuật cao."
    "Cảnh sát. Chắc chắn là bọn họ rồi."
    "Chẳng còn cách nào chống cự, tôi đưa tay và thở dài."
    main "Vậy là hết."
    $ change_chapter += 1
return
