label chap2_3:
    "Chắc là phải làm rồi."
    "Sau khi uống một viên thuốc và cầm sẵn luôn hộp thuốc trên tay. Tôi liều mình hít một hơi thật sâu thứ không khí lẫn đầy mùi hương chết chóc đó và tiến đến gần cô ta, rồi cứ thế nhấc bổng cơ thể đó lên bằng cả hai tay."
    "Hệt như việc tôi đã làm với cô gái này khi cô ta xuất hiện trong nhà tôi vậy."
    "Tôi cố nhớ lại xem bản thân đã làm thế nào để bế cô gái này lên ở lần trước, thế nhưng suy nghĩ tôi lúc này chẳng khác gì một mớ bòng bong vậy."
    "Chèn vào đó là những cơn đau thắt như muốn bóp ngạt lấy trái tim tôi."
    "Phổi tôi như bị thiêu đốt bởi thứ mùi hương đầy ám muội này, chỉ cần hít một hơi thôi mà tôi cũng có cảm giác như mình đang hít lấy khí ga để bổ sung nhiên liệu cho đám cháy ở cổ họng."
    "Toàn bộ cơ thể tôi bủn rủn, chẳng còn lức lực để có thể đứng vững. Đầu óc tôi choáng váng chẳng còn phân biệt nổi trước sau trái phải, tất cả đều đang quay cuồng."
    "Tuy nhiên!"
    "Cố gắng tự cắn vào đôi môi khô đến nứt nẻ của mình, tôi lấy lại chút ý chí để lê lết từng bước chân nặng nề."
    "Song, mỗi lần tôi di chuyển, cơ thể quá mức mềm mại đó lại chà xát lên người tôi thông qua tận bao nhiêu lớp vải."
    "Mái tóc mềm mại, cánh tay mềm mại, làn da mềm mại, đôi môi mềm mại, mềm mại, mềm mại, mềm mại, mềm mại, mềm mại..."
    "Đầu tôi chẳng còn có thể suy nghĩ bình thường, nó bắt đầu lặp đi lặp lại những từ ngữ vô nghĩa như muốn kéo tôi rơi xuống hố đen tuyệt vọng. Thế nhưng, tôi vẫn cố gắng bước đi."
    "Cuối cùng, ngay khoảng khắc tôi đến trước được cái cầu thang ngay cạnh bức tường, tôi chẳng còn chần chừ mà cụng thẳng đầu mình vô đó."
    "Có vẻ cú cụng hơi mạnh quá khiến cho máu bắt đầu chảy xuống, che đi một phần tầm nhìn của tôi."
    "Cũng nhờ vậy, mùi máu đã lấp đi được phần nào mùi hương như muốn mang người khác sang thế giới bên kia."
    "Thế nhưng, sự tỉnh táo cũng chỉ giữ được trong một khoảng khắc ngắn trước khi cơn choáng váng do đầu bị tổn thương cùng với việc có một cô gái đang nằm trong vòng tay của tôi."
    "Cơ mà chết kiểu này tính ra cũng hạnh phúc đấy nhỉ?"
    "Khoan đã, tôi đang nghĩ cái gì vậy? Não mất khả năng nhận thức rồi à? Bình tĩnh nào, phải giữ mình tỉnh táo, phải tỉnh táo."
    "Mở hộp thuốc đang trên đà rơi khỏi tay, tôi lấy ra một viên thuốc nữa. Chẳng còn bận tâm rằng thứ này là gì, tôi cho viên thuốc mới lấy ra thẳng vào miệng."
    "Tuy nhiên, tôi chưa nuốt xuống hẳn mà bắt đầu dùng răng cắn nó đến khi vỡ vụn."
    "Cái mùi hương đắng nghét cùng cảm giác buồn nôn nơi cuống họng đã phần nào bài trừ đi cơn mê của tôi. Cố gắng đảo đống vụn thuốc bằng lười, tôi muốn vòm miệng mình cảm nhận từng chút một, từng chút một của cái vị đắng chẳng bao giờ thay đổi đó."
    main "Ọe..."
    "Thế nhưng, cũng chính nhờ vậy mà quãng đường đi xuống tầng hầm của tôi trở nên dễ dàng hơn rất nhiều."
    "Sau khi đã đặt cô ta ngồi yên vị ở một cái ghế cuối góc phòng, tôi mới có thể tiếp tục công việc của mình. Rất may là cái vị đắng đến kinh tởm đó vẫn còn sót lại trong miệng tôi nên tôi sẽ tạm thời quên được sự hiện diện của cô gái đó trong cái tầng hầm chật chội và kín mít này."
    main "Kiệt sức rồi."
    "Tôi gần như muốn gục ngay tại chổ. Việc phải làm việc lao lực suốt hai ngày đã khiến cơ thể tôi sắp quá tải. Nhưng khi phải bế cô nàng này xuống hầm nữa thì nó báo động đỏ rồi."
    main "Còn làm gì thêm nữa thì chết trước ngày bệnh phát mất."
    "Nghĩ thế nên tôi đi ngủ. Dù gì chỉ còn vài bước nữa là con tàu kia sẽ hoàn thành thôi nên nghỉ tý cũng chả sao."
    scene black with dissovle
    scene bg_ham with fade
    "Mọi thứ đã gần như hoàn thành, giờ chỉ còn một việc duy nhất là năng lượng nữa thôi."
    "Vì đã không lấy cái lõi năng lượng kia nên giờ đây tôi phải nghĩ ra cách khác để cấp năng lượng cho nó mới được."
    "Chẳng biết dùng thứ gì cả nên tôi đành phải sử dụng nguồn điện. Nhưng điện thì tôi nghĩ nó sẽ không đủ để cho cái 'Con Quái Thú' này chạy nổi đâu."
    "Lí do tôi gọi nó là 'Quái thú' vì nó rất ngốn điện. Bởi thế nên tôi đã tạo ra một máy phát điện trong khu vực gần động cơ."
    "Tận dụng nguồn gió ma sát với tàu trong lúc bay là có thể làm quay tubin rồi. Nhưng nó không thể quá to được nên tôi đã tận dụng những kiến thức và công nghệ của thời đại và tạo ra thêm máy khuết đại năng lượng."
    "Nghe thì con tàu này lại có vẻ như rất được việc đấy nhưng so với nguồn năng lượng mà các loại tàu bay thời nay dùng thì chỉ như so sánh cốc nước muối với biển thôi."
    "Vì tận dụng nguồn gió, hay nói cách khác là sự chuyển động của không khí khi con tàu bay trong khí quyển nên gần như là nó sẽ chạy rất trơn tru mà chẳng tốn một chút nguyên liệu thêm nào nữa."
    "Nhưng khi ra ngoài không gian thì lại khác. Nhưng mà tôi có định ra ngoài không gian đâu, nên chắc như này là ổn."
    "Trước khi muốn tubin trong máy phát điện chạy nhờ sức gió thì tôi phải cho nó một nguồn năng lượng để cho nó bay trước đã."
    "Nên là tôi đã chuẩn bị một thứ gần giống như pin dự trữ phòng tình huống hỏng máy phát điện để còn năng lượng đáp xuống khẩn cấp. Cũng như trước khi bay lên trời."
    "Giờ việc của tôi là nạp đầy điện thôi."
    "Lấy máy vặn ốc tự động, tôi cạy phần ống dẫn dây trong nhà ra.Sau đó, tôi nối dài nó xuống tầng hầm. Cắm nó vào một cái máy khuết đại dòng điện khác nhỏ hơn để nạp điện cho pin dự phòng."
    play sound machine
    main "Cái này vào đây, còn cái này... nối vào đây nữa là xong. Phù."
    main "Chỉ còn việc cắm nó vào phần vốn chứa lõi của cỗ máy thôi."
    "Nói đoạn, tôi kéo đoạn dây to bằng cả cổ tay đến gần cỗ máy, leo lên phần thân nó bằng thang bảo trì và cắm phần chốt dây vào ngay phía trên phần lõi."
    play sound electric3
    "Thế nhưng, vào khoảng khắc mà tôi cắm chốt dây vào, mọi thứ xung quang liền bị bao phủ bởi một màu đen sâu thẳm."
    main "Mất điện à?"
    main "Mà cũng không đúng lắm, thời buổi này mất điện còn hiếm hơn việc trúng số nữa."
    main "Thôi xong, nếu không phải mất điện thì chỉ còn một cách để giải thích."
    "Cỗ máy này đã rút hết toàn bộ điện nơi đây. Và nơi đây nói chính xác thì là thành phố này."
    "Bởi lẽ nguồn điện trong nhà tôi liên kết với toàn bộ căn nhà trong chung cư này"
    "Và nguồn điện của chung cư lấy một phần tù trụ điện tổng trong thành phố."
    main "Nhưng chỉ với một viên pin dự phòng thôi mà đã như thế à?"
    "Dù biết nó sẽ rất ngốn điện nhưng tôi không ngờ là nó lại khủng khiếp đến thế."
    main "Chuyện này có vẻ không ổn lắm nhỉ?"
    "Thứ gì đó để chiếu sáng cái đã."
    "Lần mò từng bước trong bóng tối, tôi leo xuống khỏi thang bảo trì và an toàn đặt chân xuống sàn nhà."
    "Trong lúc tôi đang quơ ngang tay, cố xác định lại khung cảnh xung quanh thừ từ phía sau lưng..."
    "Một luồng sáng xanh bất ngờ đổ bộ và bao phủ lấy cả tầng hầm."
    "Bất giác quay lưng, tôi cố nhìn vào thứ đang tỏa ra sắc xanh huyền ảo đó."
    "Từ khe hở của thứ kết cấu không mấy bền bỉ, con tàu tôi vừa chế đạo đang ánh thên thứ màu lam rực rỡ hệt như con tàu nằm sâu phía trong con hẻm."
    "Ngay lập tức bị thu hút, tôi tiến đến gần con tàu và mở buồng lái ra. Cánh cửa bỗng bật mở cũng với một làn khói trắng hòa vẫn vào ánh sáng xanh mờ ảo tạo nên một cung cảnh đầy ấn tượng."
    "Nhìn vào bảng điều khiển đang được bật lên trong con tàu, đập vào mắt tôi chính là một màn hình duy nhất hiển thị nguồn năng lượng hiện tại."
    "Ba mươi bảy phần trăm."
    main "Thứ này hao năng lượng đến mức nào vậy chứ?"
    "Lượng điện đủ cho cả một thành phố dùng và được khuết đại lên 10 phần trăm mà chỉ sạc được ba mươi bảy phần trăm? Tôi bắt đầu lo lắng liệu những máy phát điện của tôi có đủ để gánh nổi cả cái thứ này bay lên được không."
    "Tuy phàn nàn là thế, tôi vẫn bị trí tò mò thu hút và ngồi vào bên trong. Ngồi xuống cái ghế lấy ra từ một cỗ xe cũ vứt lây lất đầu đường."
    "Tôi đặt tay lên cái cần điều khiển lấy từ một cái điều khiển từ xa dành cho drone."
    "Ấn nút đóng cửa, tôi từ từ quan sát chuyển động có phần hơi chậm chạp của cánh cửa kính. Được thiết kế như một cái cửa kéo để phù hợp với không gian, thay vì một cái cửa mở như bản gốc."
    main "Hệ thống phòng thủ, check. Rada, check. Nút thoát hiểm, check. Cảm biến quang phổ, cảm biến nhiện, check. Hộp dụng cụ và một vài bộ phận để thay thế, check."
    main "Pin dự trữ, ba mươi bốn phần trăm, check."
    main "Tất cả điều được kết nói với bảng điều khiển. Còn thiếu thứ gì nữa không nhỉ...?"
    main "À phải rồi! Camera sau!"
    #play sound rầm
    "Trong lúc tôi lấy hộp dụng cụ để kiểm tra lại lỗi, một âm thanh lớn phát ra ngay gần đây khiến tôi giật bắn mình và đập đầu vào phần trên của con tàu."
    main "Ui! Đau!"
    "Kế đến, một loạt âm thanh nghe như tiếng bước chân phát ra dồn dập trên đầu tôi. Ngửa cổ lên nhìn, đập vào mắt tôi chỉ có lớp vỏ kim loại của con tàu, chẳng thể nhìn thấy gì hơn."
    "Và cho dù không có con tàu ở đây thì thứ tôi thấy cũng chỉ là lớp trần bê tông."
    "Có ai đó đang ở trong nhà tôi, hơn nữa còn rất nhiều."
    #import game here
    main "Được rồi!"
    "Không để thời gian chết trôi đi, tôi vội dùng lực mở cánh cửa bằng tay chứ không thể chờ nó từ từ mở ra được nữa. Khẩn trương cầm lấy hộp thuốc và di chuyển cô gái kia vào trong con tàu, tôi ngồi vào và đóng cửa tàu lại."
    "Trong tình cảnh đó, tôi chẳng còn có thể quan tâm nổi mùi gì đang ở trước mũi, hay mình đang động vào chỗ nào của cô gái kia. Điều tôi cần là làm sao đưa cô ta lên tàu nhanh nhất có thể."
    "Cũng may rằng mọi thứ vừa kịp lúc trước khi bọn người ở bên trên chạy xuống dưới này."
    "???" "Này! Cậu trai kia, mau đưa hai tay lên đầu!"
    "Một cảnh sát chĩa súng vào tôi thông qua lớp kính ở phần đầu tàu. Thế nhưng tôi chẳng quan tâm lắm vì cái kính này được lấy từ con tàu phế liệu ở con hẻm mà."
    "Tôi đã thử kiểm tra độ va đập của nó rồi. Ít nhất là đủ cứng để đạn thông thường không thể xuyên thủng."
    "Còn lớp vỏ thì được làm từ cái con tàu kia nốt. Chưa kể trong lúc tái máy cái nằm ở con hẻm tôi đã học được một công nghệ khá hữu dụng cho tình huống này."
    "Tôi gạt cần gạt cạnh tay mình. Một lớp bảo vệ bằng nano bắt đầu bọc quanh con tàu với tốc độ âm thanh, gia tăng khả năng chống chịu của con tàu"
    "Cỡ này thì một hai quả lựu đạn hay vài trăm viên đạn cũng không thành vấn đề. Nhưng nếu hơn thì sẽ khá là rắc rối đấy. Bật màn hình hiển thị, tôi quan sát xung quanh một lúc trước khi khởi động động cơ."
    "Lẫn trong đám cảnh sát vừa chạy xuống tầng hầm là một kẻ mặt vest đen với ánh mắt sắc lạnh. Một kẻ chỉ nhìn thôi cũng biết là nguy hiểm. Ngay khi ánh mắt của cả hai chạm nhau, tôi chẳng còn đủ lý trí để chần chừ nữa."
    "Khởi động con tàu, tôi nâng dần độ cao và phá bỏ lớp trần ngăn cách nhà tôi với tầng hầm bên dưới. Gạt cần điều khiển ra sau, tôi phá hủy một bức tường nữa để kiếm đường thoát thân."
    "Cứ thế, tôi phóng thẳng vào bầu trời đêm phủ đầy mây xám và bây khỏi nơi mà mình đã gắn bó khá lâu."
    "Con tàu này sẽ dễ bị bắt kịp đấy."
    "Nhưng."
    main "Thì sao chứ?"
    "Không còn giấu nổi sự phấn khích, tôi nở một nụ cười tự mãn mà quên mất rằng. Ngồi cùng với tôi trong con tàu chật chội này không ai khác ngoài một mầm bệnh chết người."
